spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./beginner;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: beginner
    password: qwer1234
    hikari:
      maximum-pool-size: 3
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: exmail.jetwell.com.tw
    port: 587
    username: 帳號@ginmao.com.tw
    password: 密碼
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: exmail.jetwell.com.tw
  h2:
    console:
      enabled: true
ginmao:
  admin:
    mail-from: 帳號@ginmao.com.tw
server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:gtweb.p12
    key-store-password: qwer1234
    key-alias: gtweb
  port: 4343
