version: '3'

services:
  mysql-gtweb:
    image: mysql:latest
    restart: always
    container_name: mysql-beginner
    platform: linux/amd64
    deploy:
      resources:
        limits:
          memory: 2G
    ports:
      - 3306:3306
    volumes:
      - ../docker/mysql-beginner/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qwer1234
      - MYSQL_USER=beginner
      - MYSQL_PASSWORD=qwer1234
      - MYSQL_DATABASE=beginner
      - TZ=Asia/Taipei
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_0900_ai_ci'
      - '--default-time-zone=+08:00'
      - '--skip-character-set-client-handshake'
      - '--default-authentication-plugin=mysql_native_password'
      - '--log-bin-trust-function-creators=1'
      - '--lower_case_table_names=1'
